import Link from "next/link";
import { BrandLogo } from "@/components/ui/brand-logo";

const features = [
  ["Mensalidades sob controle", "Veja pagamentos pendentes e atrasados sem procurar conversa por conversa."],
  ["Chamada em segundos", "Abra a turma no celular e marque presença com poucos toques."],
  ["Cadastro que faz sentido", "Aluna, responsável, turma e mensalidade reunidos em uma ficha simples."],
];

function ProductPreview({ title, type }: { title: string; type: "payments" | "attendance" | "student" | "dashboard" }) {
  const content = type === "payments" ? <><div className="flex justify-between text-xs"><b>Marina Souza</b><span className="text-[#b3374a]">Atrasado</span></div><div className="flex justify-between text-xs"><span>Luiza Ferreira</span><span className="text-[#24734f]">Pago</span></div><div className="flex justify-between text-xs"><span>Camila Alves</span><span className="text-[#a86712]">Pendente</span></div></> : type === "attendance" ? <><div className="flex justify-between text-xs"><b>Marina Souza</b><span className="rounded bg-[#e7f4ed] px-2 py-1 text-[#24734f]">Presente</span></div><div className="flex justify-between text-xs"><b>Luiza Ferreira</b><span className="rounded bg-[#e7f4ed] px-2 py-1 text-[#24734f]">Presente</span></div><div className="flex justify-between text-xs"><b>Camila Alves</b><span className="rounded bg-[#f9e9eb] px-2 py-1 text-[#b3374a]">Faltou</span></div></> : type === "student" ? <><p className="text-lg font-semibold">Marina Souza</p><p className="text-xs text-neutral-500">Ballet Infantil A</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><span className="rounded-lg bg-[#f8f0f2] p-2">Responsável<br/><b>Ana Souza</b></span><span className="rounded-lg bg-[#f8f0f2] p-2">Mensalidade<br/><b>R$ 180,00</b></span></div></> : <><div className="grid grid-cols-3 gap-2"><span className="rounded-lg bg-[#f8f0f2] p-2 text-xs">Alunas<br/><b className="text-base">46</b></span><span className="rounded-lg bg-[#e7f4ed] p-2 text-xs">Recebido<br/><b className="text-base">R$ 5.2k</b></span><span className="rounded-lg bg-[#fdf4e5] p-2 text-xs">Pendente<br/><b className="text-base">R$ 720</b></span></div><div className="mt-3 h-16 rounded-lg bg-neutral-50 p-2 text-xs">Aulas de hoje <span className="float-right text-[#6f2945]">Fazer chamada</span></div></>;
  return <div className="rounded-2xl border border-[#e8e3e3] bg-white p-3 shadow-[0_20px_45px_rgba(73,39,52,.11)]"><div className="mb-3 flex items-center gap-1.5 border-b border-neutral-100 pb-2"><i className="h-2 w-2 rounded-full bg-[#d99aaa]"/><i className="h-2 w-2 rounded-full bg-[#ead9df]"/><span className="ml-1 text-[10px] font-semibold text-neutral-500">{title}</span></div><div className="space-y-3">{content}</div></div>;
}

export default function Home() {
  return <main className="overflow-hidden bg-[#faf9f7] text-[#211b1e]">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><BrandLogo/><nav className="hidden gap-7 text-sm text-[#746c70] md:flex"><a href="#como-funciona">Como funciona</a><a href="#recursos">Recursos</a><a href="#oferta">Planos</a></nav><Link href="/login" className="text-sm font-semibold text-[#7A1F3D] hover:text-[#5A1730]">Entrar</Link></header>
    <section className="relative mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-14 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:pb-28 lg:pt-24"><div className="max-w-xl"><p className="mb-5 text-xs font-bold uppercase tracking-[.16em] text-[#893c5c]">Gestão para studios de ballet</p><h1 className="font-display text-5xl leading-[1.02] tracking-[-.035em] sm:text-6xl">Pare de administrar seu studio pelo caderno e WhatsApp.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-[#746c70]">Controle alunas, turmas, presenças e mensalidades em um único sistema criado para studios de ballet.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/cadastro" className="rounded-xl bg-[#6f2945] px-6 py-4 text-center text-sm font-bold tracking-wide text-white shadow-lg shadow-[#6f2945]/15 transition hover:bg-[#552036]">QUERO ORGANIZAR MEU STUDIO</Link><a href="#como-funciona" className="rounded-xl border border-[#e8e3e3] bg-white px-6 py-4 text-center text-sm font-semibold transition hover:border-[#ce94a8]">Conhecer o sistema</a></div><p className="mt-4 text-xs text-[#746c70]">Comece sem complicação. Feito para a rotina real do seu studio.</p></div><div className="relative mx-auto w-full max-w-xl self-center rounded-[1.75rem] bg-[#f1e0e5] p-5 sm:p-8"><div className="absolute -right-5 top-12 hidden rounded-xl bg-white p-3 shadow-md sm:block"><p className="text-[10px] text-neutral-500">Recebido no mês</p><b className="text-sm text-[#24734f]">R$ 5.280,00</b></div><ProductPreview title="Visão geral do studio" type="dashboard"/><div className="absolute -bottom-7 -left-3 w-44 sm:-left-10 sm:w-52"><ProductPreview title="Mensalidades" type="payments"/></div></div></section>
    <section id="como-funciona" className="border-y border-[#e8e3e3] bg-white py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="text-center text-xs font-bold uppercase tracking-[.16em] text-[#893c5c]">Da bagunça à rotina leve</p><h2 className="mx-auto mt-3 max-w-2xl text-center font-display text-4xl leading-tight">Menos tarefas espalhadas. Mais tempo para ensinar.</h2><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-neutral-200 p-6"><p className="text-xs font-bold uppercase tracking-widest text-neutral-400">Antes</p><ul className="mt-5 space-y-3 text-[#746c70]"><li>Planilhas e caderno</li><li>Mensagens espalhadas</li><li>Cobranças individuais</li><li>Mensalidades esquecidas</li></ul></div><div className="rounded-2xl bg-[#6f2945] p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-[#e4c4ce]">Com BalletPro</p><ul className="mt-5 space-y-3"><li>Alunas e turmas organizadas</li><li>Chamada rápida no celular</li><li>Mensalidades visíveis</li><li>Cobrança pelo WhatsApp</li></ul></div></div></div></section>
    <section id="recursos" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#893c5c]">O essencial, bem resolvido</p><h2 className="mt-3 font-display text-4xl leading-tight">A operação do studio em uma tela clara.</h2><div className="mt-8 space-y-6">{features.map(([title, text], i) => <div key={title} className="flex gap-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#f1e0e5] text-xs font-bold text-[#6f2945]">0{i + 1}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-[#746c70]">{text}</p></div></div>)}</div></div><div className="grid gap-5 sm:grid-cols-2"><div className="sm:pt-12"><ProductPreview title="Mensalidades • Setembro" type="payments"/></div><ProductPreview title="Chamada • Ballet Infantil A" type="attendance"/><div className="sm:col-span-2 sm:mx-auto sm:w-3/4"><ProductPreview title="Ficha da aluna" type="student"/></div></div></div></section>
    <section id="oferta" className="bg-[#2d101b] px-5 py-20 text-white"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e4c4ce]">BalletPro</p><h2 className="mt-3 font-display text-4xl">Organize seu studio com leveza.</h2><p className="mx-auto mt-4 max-w-xl text-[#ead9df]">Tenha a rotina de alunas, turmas, presença e mensalidades num lugar que sua equipe entende de primeira.</p><div className="mx-auto mt-9 max-w-sm rounded-2xl bg-white p-7 text-[#211b1e] shadow-2xl"><p className="text-sm font-semibold">Plano BalletPro</p><p className="mt-3 text-4xl font-semibold">Consulte as condições</p><p className="mt-2 text-sm text-[#746c70]">Acesso completo à gestão do seu studio.</p><Link href="/cadastro" className="mt-6 block rounded-xl bg-[#6f2945] px-5 py-4 text-sm font-bold tracking-wide text-white transition hover:bg-[#552036]">QUERO ORGANIZAR MEU STUDIO</Link></div></div></section>
    <footer className="mx-auto flex max-w-7xl items-center justify-between px-5 py-8 text-xs text-[#746c70] lg:px-8"><BrandLogo/><span>Gestão feita para studios de ballet</span></footer>
  </main>;
}
